version: '3'

services:
  db:
    environment:
      POSTGRES_USER: ${POSTGRES_ISERVICE_DEV_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ISERVICE_DEV_PASS}
      POSTGRES_DB: ${POSTGRES_ISERVICE_DEV_DB}
    container_name: iservice-db
    image: mdillon/postgis
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    build:
      context: .
    container_name: iservice-api
    ports:
      - "5000:5000"
    volumes:
      - ./application:/application
      - ./alembic:/alembic
    depends_on:
      - db
    env_file: .env
    networks:
      - default
    restart: always