"""Add reference to store in product table

Revision ID: 53f6875aa5d2
Revises: 6fb09fc3b3e6
Create Date: 2020-08-26 23:44:08.923657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f6875aa5d2'
down_revision = '6fb09fc3b3e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('store_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'product', ['store_id'])
    op.create_foreign_key(None, 'product', 'store', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'store_id')
    # ### end Alembic commands ###
