"""Reverse foreign key

Revision ID: 6fb09fc3b3e6
Revises: 46bd486eca36
Create Date: 2020-08-21 19:56:07.893825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb09fc3b3e6'
down_revision = '46bd486eca36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('partner_store_id_key', 'partner', type_='unique')
    op.drop_constraint('partner_store_id_fkey', 'partner', type_='foreignkey')
    op.drop_column('partner', 'store_id')
    op.add_column('store', sa.Column('partner_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'store', ['partner_id'])
    op.create_foreign_key(None, 'store', 'partner', ['partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store', type_='foreignkey')
    op.drop_constraint(None, 'store', type_='unique')
    op.drop_column('store', 'partner_id')
    op.add_column('partner', sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('partner_store_id_fkey', 'partner', 'store', ['store_id'], ['id'])
    op.create_unique_constraint('partner_store_id_key', 'partner', ['store_id'])
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
